version: '3.7'

services:

  dev-tls:
    build:
      context: .
      dockerfile: ./docker/dev-tls/Dockerfile
    depends_on:
      - web
    links:
      - web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - target: 443
        published: 443
        protocol: tcp


  web:
    build:
      context: ./BipBopOne-WebApp
      dockerfile: Dockerfile
    volumes:
      - '.:/BipBopOne-WebApp'
      - './node_modules'


  webar:
    build:
      context: ./BipBopOne-WebApp-AR
      dockerfile: Dockerfile
    volumes:
      - '.:/BipBopOne-WebApp-AR'
      - './node_modules'
    ports:
      - '9000:9000'